name: ci-cd
on: [ push ]

jobs:
  service-test:
    runs-on:
      labels: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        name: Setup Java and Gradle
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - id: test
        name: Test Application
        shell: bash
        run: ./gradlew test --no-daemon
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/test-results/**/TEST-*.xml"
        if: always()
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        with:
          name: Gradle Tests
          path: "**/test-results/**/TEST-*.xml"
          reporter: java-junit
